FROM node:${NODE_VERSION:-14.19.2} AS deps

# Set up working directory
WORKDIR /usr/app

# Set noninteractive mode for apt-get and update package sources
ENV DEBIAN_FRONTEND=noninteractive

# Update Debian sources and install necessary packages
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list && \
    sed -i 's|security.debian.org|archive.debian.org/|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends musl-dev && \
    ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1 && \
    rm -rf /var/lib/apt/lists/*

# Copy only the package files first to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies using yarn
# RUN yarn install --frozen-lockfile

# Install pm2 globally
RUN npm install -g pm2 && \
    rm -rf /usr/share/doc /usr/share/man /tmp/*

# Copy the remaining application source code
COPY . .

# Configure SSH for GitHub access
RUN mkdir -p ~/.ssh && \
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# Start the application
CMD ["node", "index.js"]
